### PR TITLE
[bug] make sure vcpkgpath is set, read vcpkgpath from env, skip toolchain set when it was set before.

### LINKED ISSUE #5: Extension referring to Window VCPKG path when calling set triplet from linux
Screenshot from 2023-11-18 13-11-25

The path shown above is the path on Windows. Also, the path shown is incorrect, even for Windows (my vcpkg is in D:tools/vcpkg. I am getting this error by calling the set host/target triplet on Linux (Ubuntu 22.04).
I am using manifest mode.
Here are the contents of my settings.json

```json
{
  "cmake.configureArgs": [
    "-DVCPKG_APPLOCAL_DEPS=ON",
    "-DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON",
    "-DVCPKG_MANIFEST_MODE=ON",
    "-DVCPKG_TARGET_TRIPLET=x64-linux"
  ],
  "vcpkg.general.enable": true,
  "vcpkg.target.hostTriplet": "-linux",
  // use x64-linx / arm64-osx
  "vcpkg.target.defaultTriplet": "x64-linux",
  "vcpkg.target.useStaticLib": false,
  "cmake.configureSettings": {
    "CMAKE_TOOLCHAIN_FILE": "$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
  },
  "cmake.debugConfig": {
    "cwd": "${workspaceFolder}"
  },
  "vcpkg.target.installDependencies": true,
  "vcpkg.target.preferSystemLibs": false,
  "vcpkg.target.useManifest": true,
  "vcpkg.target.useDynamicCRT": false,
  "cSpell.words": ["assimp", "glew", "glfw", "imgui", "imguizmo", "opengl"]
}

```

Note: The automatic triplet change is working correctly.

### PR DESCRIPTION
**Pull request by JackBoosY**
Fixes #5

### CODE REVIEW

File: src/configuration.ts [hunk 1]
```diff
@@ -172,6 +173,39 @@ export class ConfigurationManager implements vscode.Disposable
...
+
+        if (envVar !== undefined && envVar.value !== undefined && envVar.value.length !== 0 && await this.isVcpkgExistInPath(envVar.value))
+        {
+            return envVar.value;
+        }
+
+        return undefined;
+    }
+
+    private async getVcpkgPath()
```
Comment (JackBoosY) [inline src/configuration.ts]: We may need to create a new structure `vcpkgPath` and return with it in the future since it should contains one of 2 parts:
- `$ENV{VCPKG_ROOT}`
- The real absoulte path

which will support cross-platform development.

File: src/configuration.ts [hunk 2]
```diff
@@ -352,6 +405,15 @@ export class ConfigurationManager implements vscode.Disposable
 
     private async addVcpkgToolchain(vcpkgRoot : string)
     {
+        let originToolchain = this.getCMakeVcpkgToolchain();
+        if (originToolchain !== undefined)
```
Comment (JackBoosY) [inline src/configuration.ts:455]: This can be a bit confusing:
1. What should we do if the vcpkg path in the vcpkg toolchain that the user has set is inconsistent with the vcpkg path set in the current extension?
2. If the user disables vcpkg in the extension, the vcpkg toolchain should be removed from cmake settings because this will affect the cmake configuration. At this point, should we inform the user or let the user make a choice?

File: src/configuration.ts [hunk 3]
```diff
@@ -172,6 +173,39 @@ export class ConfigurationManager implements vscode.Disposable
         return {arch: arch, os: os};
     }
 
+    private async getVcpkgPathFromEnv()
+    {
+        // let envVar = process.env.VCPKG_PATH;
```
Comment (JackBoosY) [inline src/configuration.ts]: Finally, should we use it instead of `environmentVariableCollection` since `environmentVariableCollection` requires `vscode.ExtensionContext` which cannot be obtained from the test suite.

Related: https://github.com/microsoft/vscode/issues/152806

**Comment by JackBoosY** [comment]
BTW, after fixing this bug, I will first add test cases and refactor the code because the code hierarchy is unclear and difficult to extend.

File: src/configuration.ts (hunk 2 above)
Comment (Pipe-Runner) [reply src/configuration.ts:455]: I think the problem here is multiple sources of truth. In my opinion, the user would generally prefer using the env variable since it encourages a cross-platform build system with no change. But you should decide on one source of truth. Either let the extension setting decide everything or use user-provided path in settings.json as a source of truth.

File: src/configuration.ts (hunk 3 above)
Comment (Pipe-Runner) [reply src/configuration.ts]: I am not so sure about this. I am not well versed in this to add my input.

File: src/configuration.ts (hunk 1 above)
Comment (JackBoosY) [reply src/configuration.ts]: How about this: return the user's write string directly and check in `isVcpkgExistInPath` whether it is an environment variable.
So we don't need to care about such thing in any functions except the validation function.

File: src/configuration.ts (hunk 2 above)
Comment (JackBoosY) [reply src/configuration.ts:455]: I think we should warn user and give them 2 choise:
- Disable vcpkg.
- Override vcpkg toolchain in cmake settings using `vcpkg.general.vcpkgPath`

File: src/configuration.ts (hunk 1 above)
Comment (Pipe-Runner) [reply src/configuration.ts]: Sounds good.

Comment (Pipe-Runner) [reply src/configuration.ts]: So will that mean if the extension detects env variable, it will ignore the path string user provides in extension settings?

File: src/configuration.ts (hunk 2 above)
Comment (Pipe-Runner) [reply src/configuration.ts:455]: Will this `$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake` match against an absolute path? Since you mentioned VScode settings have to use absolute path string.

File: src/configuration.ts (hunk 1 above)
Comment (JackBoosY) [reply src/configuration.ts]: > So will that mean if the extension detects env variable, it will ignore the path string user provides in extension settings?

No, first we use a user-supplied string (either an environment variable or an absolute path), otherwise exntesion will check the default environment variable `${VCPKG_ROOT}`.

File: src/configuration.ts (hunk 2 above)
Comment (JackBoosY) [reply src/configuration.ts:455]: > Will this `$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake` match against an absolute path? Since you mentioned VScode settings have to use absolute path string.

The validation function will handle these environment variables, so they are equivalent to the outside function.

File: src/configuration.ts [hunk 4]
```diff
@@ -352,6 +458,34 @@ export class ConfigurationManager implements vscode.Disposable
...
+            {
+                // check whether the vcpkg path in toolchain is not the same with the path in settings
+                if (this.convertToAbsolutePath(originToolchain) !== this.convertToAbsolutePath(vcpkgRoot + '/scripts/buildsystems/vcpkg.cmake'))
+                {
+                    let result = await vscode.window.showQuickPick(['Disable', 'override vcpkg toolchain'], {canPickMany: false});
+
+                    if (result === 'Disable')
+                    {
+                        vscode.window.showInformationMessage('Vcpkg will be disabled.');
+                        this.disableVcpkg();
```
Comment (JackBoosY) [inline src/configuration.ts]: This may break our intended execution flow. We should terminate the process here.

File: src/configuration.ts (hunk 1 above)
Comment (Pipe-Runner) [reply src/configuration.ts]: I am a bit confused about this. Because in the extension settings UI, you are not allowed to leave the path field blank. Also you mentioned we cannot use env variables in the path field in extension settings. So will there be a way to know where the path has been taken from. Sorry if I am asking too many questions.

Comment (JackBoosY) [reply src/configuration.ts]: Now we support to write environment variables in path field.

**Comment by JackBoosY** [comment]
@Pipe-Runner Can you please test this with:
[vcpkg-cmake-tools-2.0.9.vsix.zip](https://github.com/JackBoosY/vcpkg-vscode-extension/files/13406902/vcpkg-cmake-tools-2.0.9.vsix.zip)

**Comment by Pipe-Runner** [comment]
> @Pipe-Runner Can you please test this with:
> [vcpkg-cmake-tools-2.0.9.vsix.zip](https://github.com/JackBoosY/vcpkg-vscode-extension/files/13406902/vcpkg-cmake-tools-2.0.9.vsix.zip)
> 

I have an exam in like 2 days, I'll test this out on 23rd hopefully.

**Comment by Pipe-Runner** [comment]
> > @Pipe-Runner Can you please test this with:
> > [vcpkg-cmake-tools-2.0.9.vsix.zip](https://github.com/JackBoosY/vcpkg-vscode-extension/files/13406902/vcpkg-cmake-tools-2.0.9.vsix.zip)
> 
> I have an exam in like 2 days, I'll test this out on 23rd hopefully.

Okay I have installed the vsix file. Are there particular scenarios you would want me to test out? 
@JackBoosY 

Btw, I have changed the path to the following:
image

I hope I am using it correnctly. I have built my project on Linux, seems to work. I'll test on windows tomorrow.

**Comment by JackBoosY** [comment]
@Pipe-Runner Test the vcpkg path using the environment, resets the vcpkg toolchain, it should also use environment variables.

**Comment by Pipe-Runner** [comment]
> @Pipe-Runner Test the vcpkg path using the environment, resets the vcpkg toolchain, it should also use environment variables.

If I change the vcpkg path in vscode settings, it **does not** change the toolchain path. Also, if I give incorrect path of vcpkg in vscode settings, the extension is still functioning for some reason. It feels as if the path value is completely being ignored. I have VCPKG_ROOT set in environment variables by the way.

**Comment by JackBoosY** [comment]
> If I change the vcpkg path in vscode settings, it **does not** change the toolchain path.

Correct, currently extension will only check whether your vcpkg path is same with the toolchain path.

> Also, if I give incorrect path of vcpkg in vscode settings, the extension is still functioning for some reason. It feels as if the path value is completely being ignored. 

That's because I disabled the vcpkg binary check since it will fail on some reason.

**Comment by Pipe-Runner** [comment]
> > If I change the vcpkg path in vscode settings, it **does not** change the toolchain path.
> 
> Correct, currently extension will only check whether your vcpkg path is same with the toolchain path.
> 
> > Also, if I give incorrect path of vcpkg in vscode settings, the extension is still functioning for some reason. It feels as if the path value is completely being ignored.
> 
> That's because I disabled the vcpkg binary check since it will fail on some reason.

So what is the plan from here? Will there be a way to give a warning or error when the path's don't match?

**Comment by Pipe-Runner** [comment]
Also, here is a nice feature inspiration for the package:
https://blog.jetbrains.com/clion/2023/01/support-for-vcpkg-in-clion/

File: src/configuration.ts [hunk 5]
```diff
@@ -352,10 +458,50 @@ export class ConfigurationManager implements vscode.Disposable
...
     {
+        let originToolchain = this.getCMakeVcpkgToolchain();
+        if (originToolchain !== undefined)
+        {
+            if (fs.existsSync(originToolchain))
+            {
+                // check whether the vcpkg path in toolchain is not the same with the path in settings
+                if (this.convertToAbsolutePath(originToolchain) !== this.convertToAbsolutePath(vcpkgRoot + '/scripts/buildsystems/vcpkg.cmake'))
+                {
+                    vscode.window.showErrorMessage('Detected mismatched vcpkg toolchain!');
```
Comment (JackBoosY) [inline src/configuration.ts]: See here.
We may also need to do this check before configure cmake.
No idea how to inject vcpkg check in cmake extension.

**Comment by JackBoosY** [comment]
> Also, here is a nice feature inspiration for the package: https://blog.jetbrains.com/clion/2023/01/support-for-vcpkg-in-clion/

Yeah, most of the features are planning to implement.

File: src/configuration.ts (hunk 5 above)
Comment (JackBoosY) [reply src/configuration.ts]: This will be executed when enable vcpkg in extension.

**Comment by JackBoosY** [comment]
Please test [vcpkg-cmake-tools-2.0.9.vsix.zip](https://github.com/JackBoosY/vcpkg-vscode-extension/files/13498350/vcpkg-cmake-tools-2.0.9.vsix.zip) again.
This fixes the issue where toolchain mismatches were not reported when changing the vcpkg path.

File: src/configuration.ts (hunk 5 above)
Comment (Pipe-Runner) [reply src/configuration.ts]: > See here. We may also need to do this check before configure cmake. No idea how to inject vcpkg check in cmake extension.

After my exams, I will try to help you out with the development of this extension. If possible, you can prepare a plan and objectives and I can assist you with the work.
I'll be available from 13th December.

**Comment by Pipe-Runner** [comment]
[Screencast from 30-11-23 18:57:03.webm](https://github.com/JackBoosY/vcpkg-vscode-extension/assets/19551058/c388ebab-3439-4590-acc5-21d0a5e9431d)

@JackBoosY The flow is very confusing, to be honest.

**Comment by JackBoosY** [comment]
> @JackBoosY The flow is very confusing, to be honest.

Agreed, this will be improved after refactor code.

You can see the error message appearing in the lower right corner. If the vcpkg path does not match the path in the toolchain, the user will need to choose to disable vcpkg or overwrite the toolchain.

**Comment by JackBoosY** [comment]
Please test again: [vcpkg-cmake-tools-2.0.9.vsix.zip](https://github.com/JackBoosY/vcpkg-vscode-extension/files/13522076/vcpkg-cmake-tools-2.0.9.vsix.zip). I fixed the detection logic when modifying vcpkg path in config.

**Comment by Pipe-Runner** [comment]
> > @JackBoosY The flow is very confusing, to be honest.
> 
> Agreed, this will be improved after refactor code.
> 
> You can see the error message appearing in the lower right corner. If the vcpkg path does not match the path in the toolchain, the user will need to choose to disable vcpkg or overwrite the toolchain.

Yes, I find the error message helpful. But did you notice the jitter when I save the path. The settings page briefly scrolls automatically. It felt a bit buggy.

**Comment by JackBoosY** [comment]
> > > @JackBoosY The flow is very confusing, to be honest.
> > 
> > 
> > Agreed, this will be improved after refactor code.
> > You can see the error message appearing in the lower right corner. If the vcpkg path does not match the path in the toolchain, the user will need to choose to disable vcpkg or overwrite the toolchain.
> 
> Yes, I find the error message helpful. But did you notice the jitter when I save the path. The settings page briefly scrolls automatically. It felt a bit buggy.

I think this bug is in vscode side.

**Comment by JackBoosY** [comment]
If there is no other bugs, I will merge this PR.

**Comment by Pipe-Runner** [comment]
> If there is no other bugs, I will merge this PR.

Sorry, have been a bit busy this week. Can you please wait till this Sunday? I'll try to test out the changes on Saturday or Friday.

**Comment by JackBoosY** [comment]
> > If there is no other bugs, I will merge this PR.
> 
> Sorry, have been a bit busy this week. Can you please wait till this Sunday? I'll try to test out the changes on Saturday or Friday.

That's fine, thx!

**Comment by Pipe-Runner** [comment]
@JackBoosY , thank you for taking the time to develop this extension.

I have tested the latest build. I think this is much better but I have noticed a few things and you can tell me if they are intended:
1. If I give an incorrect path for vcpkg in VSC settings, then it tells me the path is incorrect and it automatically disables vcpkg 👍🏼 
2. If I give the path $env{VCPKG_ROOT}, it enables vcpkg and updates the toolchain path 👍🏼 but it does not retain my enable manifest mode settings 👎🏼 (I initially had manifest mode set to true, but whenever the path changes and there is a reenabling of vcpkg involved, it seems to reset this mode)
3. If I now change the path to /home/my_user/Apps/vcpkg, then it updates the path of toolchain to this path value as well 👍🏼 

here is a video for point 2:
[Screencast from 09-12-23 16:41:06.webm](https://github.com/JackBoosY/vcpkg-vscode-extension/assets/19551058/64051951-f0d3-4996-b662-60f0ae0dc855)

**Comment by JackBoosY** [comment]
> 2. If I give the path $env{VCPKG_ROOT}, it enables vcpkg and updates the toolchain path 👍🏼 but it does not retain my enable manifest mode settings 👎🏼 (I initially had manifest mode set to true, but whenever the path changes and there is a reenabling of vcpkg involved, it seems to reset this mode)


Yeah, extension will cleanup the vcpkg related cmake options when enable vcpkg.

**Comment by Pipe-Runner** [comment]
> > 2. If I give the path $env{VCPKG_ROOT}, it enables vcpkg and updates the toolchain path 👍🏼 but it does not retain my enable manifest mode settings 👎🏼 (I initially had manifest mode set to true, but whenever the path changes and there is a reenabling of vcpkg involved, it seems to reset this mode)
> 
> Yeah, extension will cleanup the vcpkg related cmake options when enable vcpkg.

In that case, it's perfect so far.

**Comment by JackBoosY** [comment]
Okay, I will merge this PR now.
